import type { SupabaseClient } from "@supabase/supabase-js";

import { AdminApiError, requireId, requireObject, requireText } from "@/lib/server/admin";
import type { Database, Json } from "@/types/database";

export const MAINTENANCE_TYPES = ["MAINTENANCE", "REPAIR", "INSPECTION", "CALIBRATION"] as const;
export type MaintenanceType = (typeof MAINTENANCE_TYPES)[number];

const MAINTENANCE_FIELDS = "id, instrument_id, maintenance_type, occurred_on, operator_id, result, cycle_days, next_due_on, attachment_id, remark";
type MaintenanceRow = Database["public"]["Tables"]["instrument_maintenance"]["Row"];

export type InstrumentMaintenanceView = {
  id: number;
  instrumentId: number;
  maintenanceType: string;
  occurredOn: string;
  operatorId: string;
  result: string | null;
  cycleDays: number | null;
  nextDueOn: string | null;
  attachmentId: number | null;
  remark: string | null;
};

function serializeMaintenance(row: MaintenanceRow): InstrumentMaintenanceView {
  return {
    id: row.id,
    instrumentId: row.instrument_id,
    maintenanceType: row.maintenance_type,
    occurredOn: row.occurred_on,
    operatorId: row.operator_id,
    result: row.result,
    cycleDays: row.cycle_days,
    nextDueOn: row.next_due_on,
    attachmentId: row.attachment_id,
    remark: row.remark,
  };
}

function parseDate(value: unknown, field: string, required = false) {
  if (value === undefined || value === null || value === "") {
    if (required) throw new AdminApiError(400, "INVALID_MAINTENANCE_DATE", `${field} is required.`);
    return null;
  }
  if (typeof value !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    throw new AdminApiError(400, "INVALID_MAINTENANCE_DATE", `${field} must use YYYY-MM-DD.`);
  }
  const date = new Date(`${value}T00:00:00.000Z`);
  if (Number.isNaN(date.getTime()) || date.toISOString().slice(0, 10) !== value) {
    throw new AdminApiError(400, "INVALID_MAINTENANCE_DATE", `${field} is not a valid date.`);
  }
  return value;
}

function parseCycle(value: unknown) {
  if (value === undefined || value === null || value === "") return null;
  const cycle = typeof value === "number" ? value : Number(String(value).trim());
  if (!Number.isSafeInteger(cycle) || cycle <= 0) {
    throw new AdminApiError(400, "INVALID_CALIBRATION_CYCLE", "cycleDays must be a positive integer.");
  }
  return cycle;
}

export function buildMaintenancePayload(bodyValue: unknown) {
  const body = requireObject(bodyValue);
  for (const field of ["id", "instrumentId", "operatorId", "attachmentId"]) {
    if (body[field] !== undefined) throw new AdminApiError(400, "INVALID_MAINTENANCE_FIELD", `${field} is generated by the server.`);
  }

  const maintenanceType = requireText(body.maintenanceType, "maintenanceType", 32).toUpperCase();
  if (!MAINTENANCE_TYPES.includes(maintenanceType as MaintenanceType)) {
    throw new AdminApiError(400, "INVALID_MAINTENANCE_TYPE", "Unsupported maintenance type.");
  }

  const occurredOn = parseDate(body.occurredOn, "occurredOn", true);
  const nextDueOn = parseDate(body.nextDueOn, "nextDueOn");
  const cycleDays = parseCycle(body.cycleDays);
  if (maintenanceType === "CALIBRATION" && (!cycleDays || !nextDueOn)) {
    throw new AdminApiError(400, "CALIBRATION_SCHEDULE_REQUIRED", "Calibration requires cycleDays and nextDueOn.");
  }
  if (cycleDays && nextDueOn) {
    const expected = new Date(`${occurredOn}T00:00:00.000Z`);
    expected.setUTCDate(expected.getUTCDate() + cycleDays);
    if (expected.toISOString().slice(0, 10) !== nextDueOn) {
      throw new AdminApiError(400, "CALIBRATION_SCHEDULE_MISMATCH", "nextDueOn must equal occurredOn plus cycleDays.");
    }
  }

  return {
    maintenance_type: maintenanceType,
    occurred_on: occurredOn,
    result: body.result === undefined || body.result === null || body.result === "" ? null : requireText(body.result, "result", 255),
    cycle_days: cycleDays,
    next_due_on: nextDueOn,
    remark: body.remark === undefined || body.remark === null || body.remark === "" ? null : requireText(body.remark, "remark", 2000),
  };
}

function mapMaintenanceError(error: { code?: string; message?: string }, fallback: string): never {
  const message = error.message ?? "";
  if (error.code === "42501" || message.toLowerCase().includes("permission denied")) {
    throw new AdminApiError(403, "MAINTENANCE_PERMISSION_DENIED", "Current user cannot manage maintenance records.");
  }
  if (error.code === "P0002" || message.toLowerCase().includes("not found")) {
    throw new AdminApiError(404, "INSTRUMENT_NOT_FOUND", "Instrument does not exist.");
  }
  if (error.code === "55000" || message.toLowerCase().includes("scrapped")) {
    throw new AdminApiError(409, "INSTRUMENT_SCRAPPED", "Scrapped instruments cannot receive new maintenance records.");
  }
  if (error.code === "22023") {
    throw new AdminApiError(400, "INVALID_MAINTENANCE", "Maintenance or calibration record is invalid.");
  }
  throw new AdminApiError(400, fallback, "Maintenance record operation failed.");
}

export async function loadInstrumentMaintenance(supabase: SupabaseClient<Database>, instrumentIdValue: string) {
  const instrumentId = requireId(instrumentIdValue);
  const { data, error } = await supabase
    .from("instrument_maintenance")
    .select(MAINTENANCE_FIELDS)
    .eq("instrument_id", instrumentId)
    .order("occurred_on", { ascending: false })
    .order("id", { ascending: false });
  if (error) throw new AdminApiError(500, "MAINTENANCE_LOOKUP_FAILED", "Unable to read maintenance history.");
  return ((data ?? []) as unknown as MaintenanceRow[]).map(serializeMaintenance);
}

function dateAfterDays(days: number) {
  const date = new Date();
  date.setUTCDate(date.getUTCDate() + days);
  return date.toISOString().slice(0, 10);
}

export async function loadMaintenanceReminders(supabase: SupabaseClient<Database>, days = 30) {
  if (!Number.isSafeInteger(days) || days < 0 || days > 365) {
    throw new AdminApiError(400, "INVALID_REMINDER_WINDOW", "days must be between 0 and 365.");
  }
  const { data, error } = await supabase
    .from("instrument_maintenance")
    .select(MAINTENANCE_FIELDS)
    .not("next_due_on", "is", null)
    .lte("next_due_on", dateAfterDays(days))
    .order("next_due_on", { ascending: true })
    .order("id", { ascending: true });
  if (error) throw new AdminApiError(500, "MAINTENANCE_REMINDER_LOOKUP_FAILED", "Unable to read maintenance reminders.");
  return ((data ?? []) as unknown as MaintenanceRow[]).map(serializeMaintenance);
}

export async function createInstrumentMaintenance(supabase: SupabaseClient<Database>, instrumentIdValue: string, bodyValue: unknown) {
  const instrumentId = requireId(instrumentIdValue);
  const payload = buildMaintenancePayload(bodyValue);
  const { data, error } = await supabase.rpc("record_instrument_maintenance", { _instrument_id: instrumentId, _payload: payload });
  if (error) mapMaintenanceError(error, "MAINTENANCE_CREATE_FAILED");
  const row = data && typeof data === "object" && !Array.isArray(data) ? data as Record<string, Json | undefined> : null;
  if (!row || typeof row.id !== "number") {
    throw new AdminApiError(500, "MAINTENANCE_CREATE_FAILED", "Maintenance operation returned no record.");
  }
  return serializeMaintenance(row as unknown as MaintenanceRow);
}
