-- Implements FR-METHOD-001~004, FR-TASK-002, BR-003, BR-005 and NFR-SEC-002.

create table public.experiment_method_history (
  id bigint generated by default as identity primary key,
  method_id bigint not null references public.experiment_method(id) on delete cascade,
  method_code varchar(32) not null,
  from_version varchar(32),
  to_version varchar(32) not null,
  from_status varchar(16),
  to_status varchar(16) not null,
  change_type varchar(32) not null check (change_type in ('CREATE_VERSION', 'UPDATE', 'STATUS_CHANGE')),
  operator_id uuid not null references public.sys_user(id) on delete restrict,
  remark text,
  occurred_at timestamptz not null default now()
);

create index idx_method_history_method_time
on public.experiment_method_history(method_id, occurred_at desc, id desc);

alter table public.experiment_method_history enable row level security;

drop policy if exists method_read_for_task on public.experiment_method;
create policy method_read_for_task
on public.experiment_method for select to authenticated
using (public.has_permission('task.read') or public.has_permission('resource.read'));

drop policy if exists method_manage_by_permission on public.experiment_method;
create policy method_manage_by_permission
on public.experiment_method for insert to authenticated
with check (public.has_permission('resource.manage'));

drop policy if exists method_update_by_permission on public.experiment_method;
create policy method_update_by_permission
on public.experiment_method for update to authenticated
using (public.has_permission('resource.manage'))
with check (public.has_permission('resource.manage'));

drop policy if exists method_history_read_by_permission on public.experiment_method_history;
create policy method_history_read_by_permission
on public.experiment_method_history for select to authenticated
using (public.has_permission('resource.read') or public.has_permission('task.read'));

drop policy if exists method_attachment_read_by_permission on public.attachment;
create policy method_attachment_read_by_permission
on public.attachment for select to authenticated
using (
  object_type = 'experiment_method'
  and (public.has_permission('resource.read') or public.has_permission('task.read'))
);

drop policy if exists method_attachment_manage_by_permission on public.attachment;
create policy method_attachment_manage_by_permission
on public.attachment for insert to authenticated
with check (object_type = 'experiment_method' and public.has_permission('resource.manage'));

create or replace function public.guard_method_identity()
returns trigger
language plpgsql
as $$
begin
  if new.method_code is distinct from old.method_code
     or new.version is distinct from old.version then
    raise exception 'Method identity is immutable' using errcode = '22023';
  end if;
  return new;
end;
$$;

drop trigger if exists experiment_method_identity_guard on public.experiment_method;
create trigger experiment_method_identity_guard
before update on public.experiment_method
for each row execute function public.guard_method_identity();

create or replace function public.record_method_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  change_type_value varchar(32);
  action_value varchar(32);
  before_json jsonb;
  after_json jsonb;
begin
  -- Service-role fixtures have no auth.uid(); production writes are authenticated.
  if auth.uid() is null then
    return new;
  end if;

  if tg_op = 'INSERT' then
    change_type_value := 'CREATE_VERSION';
    action_value := 'CREATE';
    before_json := null;
    after_json := jsonb_build_object('method_code', new.method_code, 'version', new.version, 'status', new.status);
    insert into public.experiment_method_history (
      method_id, method_code, from_version, to_version, from_status, to_status,
      change_type, operator_id
    ) values (
      new.id, new.method_code, null, new.version, null, new.status,
      change_type_value, auth.uid()
    );
  else
    change_type_value := case when new.status is distinct from old.status then 'STATUS_CHANGE' else 'UPDATE' end;
    action_value := case when new.status is distinct from old.status then 'STATUS' else 'UPDATE' end;
    before_json := jsonb_build_object('method_code', old.method_code, 'version', old.version, 'status', old.status);
    after_json := jsonb_build_object('method_code', new.method_code, 'version', new.version, 'status', new.status);
    insert into public.experiment_method_history (
      method_id, method_code, from_version, to_version, from_status, to_status,
      change_type, operator_id
    ) values (
      new.id, new.method_code, old.version, new.version, old.status, new.status,
      change_type_value, auth.uid()
    );
  end if;

  perform public.record_audit_event(
    'resource.manage', 'experiment_method', new.id::text, action_value,
    before_json, after_json
  );
  return new;
end;
$$;

drop trigger if exists experiment_method_history_record on public.experiment_method;
create trigger experiment_method_history_record
after insert or update on public.experiment_method
for each row execute function public.record_method_history();

revoke execute on function public.guard_method_identity() from public;
revoke execute on function public.record_method_history() from public;
