-- LIMS initial schema
-- Implements: FR-AUTH-001~005, FR-PER-001~004, FR-SAMPLE-001~006,
-- FR-TASK-001~006, FR-DATA-001~009, FR-REVIEW-001~006,
-- FR-REPORT-001~006, FR-EQUIP-001~006, FR-INVENTORY-001~006,
-- FR-ENV-001~005, FR-AUDIT-001~006, NFR-SEC-001~002, NFR-DATA-001~003.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.sys_user (
  id uuid primary key references auth.users(id) on delete restrict,
  username varchar(64) not null unique,
  real_name varchar(64) not null,
  department_id bigint,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  email varchar(128),
  last_login_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sys_role (
  id bigint generated by default as identity primary key,
  code varchar(32) not null unique,
  name varchar(64) not null,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sys_permission (
  id bigint generated by default as identity primary key,
  code varchar(64) not null unique,
  name varchar(64) not null,
  resource varchar(64) not null,
  action varchar(32) not null
);

create table public.sys_user_role (
  user_id uuid not null references public.sys_user(id) on delete cascade,
  role_id bigint not null references public.sys_role(id) on delete cascade,
  primary key (user_id, role_id)
);

create table public.sys_role_permission (
  role_id bigint not null references public.sys_role(id) on delete cascade,
  permission_id bigint not null references public.sys_permission(id) on delete cascade,
  primary key (role_id, permission_id)
);

create table public.lab_laboratory (
  id bigint generated by default as identity primary key,
  code varchar(32) not null unique,
  name varchar(128) not null,
  location varchar(255),
  manager_id uuid,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.lab_department (
  id bigint generated by default as identity primary key,
  laboratory_id bigint not null references public.lab_laboratory(id) on delete restrict,
  parent_id bigint references public.lab_department(id) on delete restrict,
  code varchar(32) not null,
  name varchar(128) not null,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (laboratory_id, code)
);

alter table public.sys_user
  add constraint sys_user_department_fk
  foreign key (department_id) references public.lab_department(id) on delete set null;

alter table public.lab_laboratory
  add constraint lab_laboratory_manager_fk
  foreign key (manager_id) references public.sys_user(id) on delete set null;

create table public.research_project (
  id bigint generated by default as identity primary key,
  project_code varchar(32) not null unique,
  name varchar(128) not null,
  owner_id uuid not null references public.sys_user(id) on delete restrict,
  description text,
  status varchar(16) not null default 'DRAFT' check (status in ('DRAFT', 'ACTIVE', 'ARCHIVED')),
  start_date date,
  end_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (end_date is null or start_date is null or end_date >= start_date)
);

create table public.sample (
  id bigint generated by default as identity primary key,
  sample_code varchar(32) not null unique,
  project_id bigint not null references public.research_project(id) on delete restrict,
  name varchar(128) not null,
  specification varchar(255),
  batch_no varchar(64),
  quantity numeric(18, 6) not null check (quantity >= 0),
  unit varchar(16) not null,
  source varchar(128),
  storage_condition varchar(255),
  status varchar(16) not null default 'REGISTERED'
    check (status in ('REGISTERED', 'PROCESSING', 'PROCESSED', 'ARCHIVED', 'DISPOSED')),
  registered_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sample_flow (
  id bigint generated by default as identity primary key,
  sample_id bigint not null references public.sample(id) on delete restrict,
  from_status varchar(16),
  to_status varchar(16) not null,
  node varchar(64) not null,
  operator_id uuid not null references public.sys_user(id) on delete restrict,
  location varchar(128),
  handover_to uuid references public.sys_user(id) on delete restrict,
  remark text,
  occurred_at timestamptz not null default now()
);

create table public.experiment_method (
  id bigint generated by default as identity primary key,
  method_code varchar(32) not null,
  name varchar(128) not null,
  version varchar(32) not null,
  scope varchar(255),
  detection_limit numeric(20, 8),
  status varchar(16) not null default 'DRAFT' check (status in ('DRAFT', 'ACTIVE', 'INACTIVE', 'EXPIRED')),
  document_id bigint,
  effective_at timestamptz,
  expired_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (method_code, version),
  check (expired_at is null or effective_at is null or expired_at >= effective_at)
);

create table public.experiment_task (
  id bigint generated by default as identity primary key,
  task_code varchar(32) not null unique,
  project_id bigint not null references public.research_project(id) on delete restrict,
  method_id bigint not null references public.experiment_method(id) on delete restrict,
  name varchar(128) not null,
  priority varchar(16) not null default 'NORMAL' check (priority in ('LOW', 'NORMAL', 'HIGH')),
  status varchar(24) not null default 'DRAFT'
    check (status in ('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_REVIEW', 'RETURNED', 'APPROVED', 'ARCHIVED')),
  planned_start date,
  planned_end date,
  remark text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (planned_end is null or planned_start is null or planned_end >= planned_start)
);

create table public.task_sample (
  task_id bigint not null references public.experiment_task(id) on delete cascade,
  sample_id bigint not null references public.sample(id) on delete restrict,
  primary key (task_id, sample_id)
);

create table public.task_assignee (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.experiment_task(id) on delete cascade,
  user_id uuid not null references public.sys_user(id) on delete restrict,
  assigned_by uuid not null references public.sys_user(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  unassigned_at timestamptz
);

create table public.task_status_history (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.experiment_task(id) on delete cascade,
  from_status varchar(24),
  to_status varchar(24) not null,
  operator_id uuid not null references public.sys_user(id) on delete restrict,
  remark text,
  occurred_at timestamptz not null default now()
);

create table public.instrument (
  id bigint generated by default as identity primary key,
  instrument_code varchar(32) not null unique,
  name varchar(128) not null,
  type varchar(64) not null,
  model varchar(64),
  manufacturer varchar(128),
  location varchar(128),
  owner_id uuid references public.sys_user(id) on delete set null,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'SCRAPPED')),
  commissioned_at date,
  next_calibration_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.task_resource (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.experiment_task(id) on delete cascade,
  resource_type varchar(32) not null check (resource_type in ('INSTRUMENT', 'INVENTORY_ITEM')),
  resource_id bigint not null,
  quantity numeric(18, 6) check (quantity is null or quantity > 0),
  unit varchar(16)
);

create table public.experiment_data (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.experiment_task(id) on delete restrict,
  sample_id bigint not null references public.sample(id) on delete restrict,
  instrument_id bigint references public.instrument(id) on delete set null,
  data_type varchar(32) not null,
  metric_name varchar(64) not null,
  raw_value numeric(20, 8),
  processed_value numeric(20, 8),
  unit varchar(16),
  source_type varchar(16) not null check (source_type in ('MANUAL', 'FILE', 'INSTRUMENT', 'API')),
  collected_at timestamptz not null,
  recorded_by uuid not null references public.sys_user(id) on delete restrict,
  remark text,
  created_at timestamptz not null default now()
);

create table public.result_review (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.experiment_task(id) on delete cascade,
  reviewer_id uuid not null references public.sys_user(id) on delete restrict,
  result varchar(16) not null check (result in ('APPROVED', 'RETURNED', 'NEED_MORE')),
  comment text,
  reviewed_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  check (result <> 'RETURNED' or nullif(trim(comment), '') is not null)
);

create table public.experiment_report (
  id bigint generated by default as identity primary key,
  report_code varchar(32) not null,
  task_id bigint not null references public.experiment_task(id) on delete restrict,
  version_no integer not null check (version_no > 0),
  status varchar(16) not null default 'DRAFT' check (status in ('DRAFT', 'PUBLISHED', 'ARCHIVED')),
  storage_path varchar(512),
  generated_by uuid not null references public.sys_user(id) on delete restrict,
  generated_at timestamptz not null default now(),
  published_at timestamptz,
  archived_at timestamptz,
  unique (report_code, version_no)
);

create table public.instrument_maintenance (
  id bigint generated by default as identity primary key,
  instrument_id bigint not null references public.instrument(id) on delete restrict,
  maintenance_type varchar(32) not null,
  occurred_on date not null,
  operator_id uuid not null references public.sys_user(id) on delete restrict,
  result varchar(255),
  next_due_on date,
  attachment_id bigint,
  remark text,
  check (next_due_on is null or next_due_on >= occurred_on)
);

create table public.inventory_item (
  id bigint generated by default as identity primary key,
  item_code varchar(32) not null unique,
  type varchar(32) not null,
  name varchar(128) not null,
  batch_no varchar(64),
  manufacturer varchar(128),
  quantity numeric(18, 6) not null default 0 check (quantity >= 0),
  unit varchar(16) not null,
  expiry_date date,
  storage_condition varchar(255),
  location varchar(128),
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE', 'EXPIRED', 'DEPLETED')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.inventory_transaction (
  id bigint generated by default as identity primary key,
  item_id bigint not null references public.inventory_item(id) on delete restrict,
  task_id bigint references public.experiment_task(id) on delete restrict,
  transaction_type varchar(16) not null check (transaction_type in ('INBOUND', 'OUTBOUND', 'ADJUSTMENT')),
  quantity numeric(18, 6) not null check (quantity > 0),
  operator_id uuid not null references public.sys_user(id) on delete restrict,
  occurred_at timestamptz not null default now(),
  remark text
);

create table public.environment_record (
  id bigint generated by default as identity primary key,
  laboratory_id bigint not null references public.lab_laboratory(id) on delete restrict,
  metric varchar(64) not null,
  value numeric(20, 8) not null,
  unit varchar(16) not null,
  threshold_min numeric(20, 8),
  threshold_max numeric(20, 8),
  collected_at timestamptz not null,
  source_type varchar(16) not null check (source_type in ('MANUAL', 'SENSOR', 'API')),
  recorded_by uuid references public.sys_user(id) on delete set null,
  status varchar(16) not null default 'NORMAL' check (status in ('NORMAL', 'WARNING', 'EXCEEDED')),
  check (threshold_max is null or threshold_min is null or threshold_max >= threshold_min)
);

create table public.attachment (
  id bigint generated by default as identity primary key,
  object_type varchar(32) not null,
  object_id varchar(64) not null,
  file_name varchar(255) not null,
  storage_path varchar(512) not null,
  file_size bigint not null check (file_size >= 0),
  content_type varchar(128) not null,
  uploaded_by uuid not null references public.sys_user(id) on delete restrict,
  uploaded_at timestamptz not null default now()
);

create table public.audit_log (
  id bigint generated by default as identity primary key,
  operator_id uuid references public.sys_user(id) on delete set null,
  object_type varchar(32) not null,
  object_id varchar(64) not null,
  action varchar(32) not null,
  before_json jsonb,
  after_json jsonb,
  ip_address inet,
  occurred_at timestamptz not null default now()
);

create index idx_lab_department_parent on public.lab_department(parent_id);
create index idx_project_owner_status on public.research_project(owner_id, status);
create index idx_sample_project_status on public.sample(project_id, status);
create index idx_sample_flow_sample_time on public.sample_flow(sample_id, occurred_at);
create index idx_task_project_status on public.experiment_task(project_id, status);
create index idx_task_status_end on public.experiment_task(status, planned_end);
create index idx_task_assignee_user on public.task_assignee(user_id, task_id);
create index idx_task_history_task_time on public.task_status_history(task_id, occurred_at);
create index idx_data_task_sample_time on public.experiment_data(task_id, sample_id, collected_at);
create index idx_review_task_time on public.result_review(task_id, reviewed_at);
create index idx_report_task_version on public.experiment_report(task_id, version_no);
create index idx_inventory_expiry_status on public.inventory_item(expiry_date, status);
create index idx_inventory_tx_item_time on public.inventory_transaction(item_id, occurred_at);
create index idx_environment_lab_time on public.environment_record(laboratory_id, collected_at);
create index idx_attachment_object on public.attachment(object_type, object_id);
create index idx_audit_object_time on public.audit_log(object_type, object_id, occurred_at);
create index idx_audit_operator_time on public.audit_log(operator_id, occurred_at);

create trigger sys_user_set_updated_at
before update on public.sys_user
for each row execute function public.set_updated_at();

create trigger sys_role_set_updated_at
before update on public.sys_role
for each row execute function public.set_updated_at();

create trigger lab_laboratory_set_updated_at
before update on public.lab_laboratory
for each row execute function public.set_updated_at();

create trigger lab_department_set_updated_at
before update on public.lab_department
for each row execute function public.set_updated_at();

create trigger research_project_set_updated_at
before update on public.research_project
for each row execute function public.set_updated_at();

create trigger sample_set_updated_at
before update on public.sample
for each row execute function public.set_updated_at();

create trigger experiment_method_set_updated_at
before update on public.experiment_method
for each row execute function public.set_updated_at();

create trigger experiment_task_set_updated_at
before update on public.experiment_task
for each row execute function public.set_updated_at();

create trigger instrument_set_updated_at
before update on public.instrument
for each row execute function public.set_updated_at();

create trigger inventory_item_set_updated_at
before update on public.inventory_item
for each row execute function public.set_updated_at();

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.sys_user (id, username, real_name, email)
  values (
    new.id,
    coalesce(
      nullif(new.raw_user_meta_data ->> 'username', ''),
      nullif(split_part(coalesce(new.email, ''), '@', 1), ''),
      'user-' || left(new.id::text, 8)
    ),
    coalesce(nullif(new.raw_user_meta_data ->> 'real_name', ''), '未命名用户'),
    new.email
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

alter table public.sys_user enable row level security;
alter table public.sys_role enable row level security;
alter table public.sys_permission enable row level security;
alter table public.sys_user_role enable row level security;
alter table public.sys_role_permission enable row level security;
alter table public.lab_laboratory enable row level security;
alter table public.lab_department enable row level security;
alter table public.research_project enable row level security;
alter table public.sample enable row level security;
alter table public.sample_flow enable row level security;
alter table public.experiment_method enable row level security;
alter table public.experiment_task enable row level security;
alter table public.task_sample enable row level security;
alter table public.task_assignee enable row level security;
alter table public.task_status_history enable row level security;
alter table public.instrument enable row level security;
alter table public.task_resource enable row level security;
alter table public.experiment_data enable row level security;
alter table public.result_review enable row level security;
alter table public.experiment_report enable row level security;
alter table public.instrument_maintenance enable row level security;
alter table public.inventory_item enable row level security;
alter table public.inventory_transaction enable row level security;
alter table public.environment_record enable row level security;
alter table public.attachment enable row level security;
alter table public.audit_log enable row level security;

create policy sys_user_select_self
on public.sys_user for select to authenticated
using (id = auth.uid());

create policy sys_user_update_self
on public.sys_user for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

comment on table public.audit_log is 'Append-only audit trail; write through server-side service functions.';
comment on table public.experiment_data is 'Raw values and processed values are stored separately and never overwritten.';
comment on table public.inventory_transaction is 'Inventory quantity changes must be represented by a transaction.';
