-- LIMS personnel profiles and capability records
-- Implements: FR-PER-001~004, NFR-SEC-001~002.

create table public.sys_position (
  id bigint generated by default as identity primary key,
  code varchar(32) not null unique,
  name varchar(64) not null,
  description varchar(255),
  status varchar(16) not null default 'ACTIVE'
    check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sys_user
  add column position_id bigint,
  add column availability_status varchar(32) not null default 'AVAILABLE'
    check (availability_status in ('AVAILABLE', 'ON_LEAVE', 'QUALIFICATION_SUSPENDED', 'UNAVAILABLE')),
  add column availability_note varchar(255),
  add column availability_until date;

alter table public.sys_user
  add constraint sys_user_position_fk
  foreign key (position_id) references public.sys_position(id) on delete set null;

create table public.sys_user_skill (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.sys_user(id) on delete cascade,
  skill_name varchar(128) not null,
  level varchar(32),
  verified_at date,
  expires_at date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at is null or verified_at is null or expires_at >= verified_at)
);

create table public.sys_user_qualification (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.sys_user(id) on delete cascade,
  qualification_name varchar(128) not null,
  certificate_no varchar(64),
  status varchar(16) not null default 'ACTIVE'
    check (status in ('ACTIVE', 'SUSPENDED', 'EXPIRED')),
  issued_at date,
  expires_at date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at is null or issued_at is null or expires_at >= issued_at)
);

create table public.sys_user_training (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.sys_user(id) on delete cascade,
  training_name varchar(128) not null,
  provider varchar(128),
  completed_at date,
  expires_at date,
  result varchar(32),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at is null or completed_at is null or expires_at >= completed_at)
);

create unique index sys_user_skill_name_uq
  on public.sys_user_skill(user_id, lower(skill_name));
create index sys_user_position_status_idx
  on public.sys_user(position_id, availability_status, status);
create index sys_user_department_availability_idx
  on public.sys_user(department_id, availability_status);
create index sys_user_qualification_user_status_idx
  on public.sys_user_qualification(user_id, status, expires_at);
create index sys_user_training_user_expiry_idx
  on public.sys_user_training(user_id, expires_at);

create trigger sys_position_set_updated_at
before update on public.sys_position
for each row execute function public.set_updated_at();

create trigger sys_user_skill_set_updated_at
before update on public.sys_user_skill
for each row execute function public.set_updated_at();

create trigger sys_user_qualification_set_updated_at
before update on public.sys_user_qualification
for each row execute function public.set_updated_at();

create trigger sys_user_training_set_updated_at
before update on public.sys_user_training
for each row execute function public.set_updated_at();

alter table public.sys_position enable row level security;
alter table public.sys_user_skill enable row level security;
alter table public.sys_user_qualification enable row level security;
alter table public.sys_user_training enable row level security;

drop policy if exists sys_user_personnel_read on public.sys_user;
create policy sys_user_personnel_read
on public.sys_user for select to authenticated
using (public.has_permission('resource.read'));

drop policy if exists sys_user_personnel_manage on public.sys_user;
create policy sys_user_personnel_manage
on public.sys_user for update to authenticated
using (public.has_permission('resource.manage'))
with check (public.has_permission('resource.manage'));

create policy sys_position_personnel_read
on public.sys_position for select to authenticated
using (public.has_permission('resource.read'));

create policy sys_position_personnel_manage
on public.sys_position for all to authenticated
using (public.has_permission('resource.manage'))
with check (public.has_permission('resource.manage'));

create policy sys_user_skill_personnel_read
on public.sys_user_skill for select to authenticated
using (public.has_permission('resource.read'));

create policy sys_user_skill_personnel_manage
on public.sys_user_skill for all to authenticated
using (public.has_permission('resource.manage'))
with check (public.has_permission('resource.manage'));

create policy sys_user_qualification_personnel_read
on public.sys_user_qualification for select to authenticated
using (public.has_permission('resource.read'));

create policy sys_user_qualification_personnel_manage
on public.sys_user_qualification for all to authenticated
using (public.has_permission('resource.manage'))
with check (public.has_permission('resource.manage'));

create policy sys_user_training_personnel_read
on public.sys_user_training for select to authenticated
using (public.has_permission('resource.read'));

create policy sys_user_training_personnel_manage
on public.sys_user_training for all to authenticated
using (public.has_permission('resource.manage'))
with check (public.has_permission('resource.manage'));

create or replace function public.record_audit_event(
  _required_permission varchar,
  _object_type varchar,
  _object_id varchar,
  _action varchar,
  _before_json jsonb default null,
  _after_json jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if _required_permission not in ('auth.user.manage', 'auth.role.manage', 'settings.manage', 'resource.manage') then
    raise exception 'unsupported audit permission';
  end if;

  if not public.has_permission(_required_permission) then
    raise exception 'permission denied';
  end if;

  insert into public.audit_log (
    operator_id, object_type, object_id, action, before_json, after_json
  ) values (
    auth.uid(), _object_type, _object_id, _action, _before_json, _after_json
  );
end;
$$;

grant execute on function public.record_audit_event(varchar, varchar, varchar, varchar, jsonb, jsonb) to authenticated;

comment on table public.sys_user is '认证用户和实验室人员身份唯一事实源；业务可用状态与账户登录状态分离。';
comment on table public.sys_user_qualification is '人员资质记录；暂停或失效状态不得被任务分配逻辑忽略。';
