-- Implements: FR-TASK-003~006, FR-TASK-008, FR-PER-002, FR-PER-004,
-- BR-001~005 and NFR-SEC-002.
-- T-205 makes task assignment and status changes server-controlled and atomic.

create table public.task_group_assignee (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.experiment_task(id) on delete cascade,
  group_id bigint not null references public.lab_group(id) on delete restrict,
  assigned_by uuid not null references public.sys_user(id) on delete restrict,
  assigned_at timestamptz not null default now(),
  unassigned_at timestamptz
);

create index idx_task_group_assignee_task_active
on public.task_group_assignee(task_id, unassigned_at);

create unique index task_assignee_active_user_uq
on public.task_assignee(task_id, user_id)
where unassigned_at is null;

create unique index task_group_assignee_active_group_uq
on public.task_group_assignee(task_id, group_id)
where unassigned_at is null;

alter table public.task_group_assignee enable row level security;

drop policy if exists task_assignee_manage_by_permission on public.task_assignee;
create policy task_group_assignee_read_by_permission
on public.task_group_assignee for select to authenticated
using (public.has_permission('task.read'));

create or replace function public.guard_task_status_update()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status is distinct from old.status
     and coalesce(current_setting('lims.task_transition', true), 'off') <> 'on' then
    raise exception 'task status must use transition RPC' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists task_guard_status on public.experiment_task;
create trigger task_guard_status
before update of status on public.experiment_task
for each row execute function public.guard_task_status_update();

create or replace function public.record_audit_event(
  _required_permission varchar,
  _object_type varchar,
  _object_id varchar,
  _action varchar,
  _before_json jsonb default null,
  _after_json jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if _required_permission not in (
    'auth.user.manage', 'auth.role.manage', 'settings.manage',
    'resource.manage', 'project.manage', 'task.read', 'task.manage', 'task.assign',
    'sample.manage'
  ) then
    raise exception 'Unsupported audit permission' using errcode = '22023';
  end if;

  if not public.has_permission(_required_permission) then
    raise exception 'Permission denied' using errcode = '42501';
  end if;

  insert into public.audit_log (
    operator_id, object_type, object_id, action, before_json, after_json
  ) values (
    auth.uid(), _object_type, _object_id, _action, _before_json, _after_json
  );
end;
$$;

create or replace function public.replace_task_assignments(
  _task_id bigint,
  _user_ids uuid[] default null,
  _group_ids bigint[] default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  task_row public.experiment_task%rowtype;
  operator_id uuid := auth.uid();
  target_user_count bigint;
  valid_user_count bigint;
  target_group_count bigint;
  valid_group_count bigint;
  target_status varchar(24);
  occurred_at timestamptz := now();
begin
  if _user_ids is null and _group_ids is null then
    raise exception 'Assignment payload required' using errcode = '22023';
  end if;

  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE')
     or not public.has_permission('task.assign') then
    raise exception 'Task assignment permission denied' using errcode = '42501';
  end if;

  select * into task_row
  from public.experiment_task
  where id = _task_id
  for update;
  if not found then
    raise exception 'Task not found' using errcode = 'P0002';
  end if;
  if task_row.status in ('PENDING_REVIEW', 'APPROVED', 'ARCHIVED') then
    raise exception 'Task is not assignable' using errcode = '22023';
  end if;

  select count(distinct id) into target_user_count
  from unnest(coalesce(_user_ids, array[]::uuid[])) as ids(id);
  select count(*) into valid_user_count
  from public.sys_user
  where id = any(coalesce(_user_ids, array[]::uuid[]))
    and status = 'ACTIVE'
    and availability_status = 'AVAILABLE';
  if target_user_count <> valid_user_count then
    raise exception 'Invalid assignee user' using errcode = '22023';
  end if;

  select count(distinct id) into target_group_count
  from unnest(coalesce(_group_ids, array[]::bigint[])) as ids(id);
  select count(*) into valid_group_count
  from public.lab_group
  where id = any(coalesce(_group_ids, array[]::bigint[]))
    and status = 'ACTIVE';
  if target_group_count <> valid_group_count then
    raise exception 'Invalid assignee group' using errcode = '22023';
  end if;

  if target_user_count = 0 and target_group_count = 0 and task_row.status <> 'DRAFT' then
    raise exception 'Task assignment required' using errcode = '22023';
  end if;

  update public.task_assignee
  set unassigned_at = occurred_at
  where task_id = task_row.id and unassigned_at is null;
  update public.task_group_assignee
  set unassigned_at = occurred_at
  where task_id = task_row.id and unassigned_at is null;

  insert into public.task_assignee (task_id, user_id, assigned_by, assigned_at)
  select task_row.id, ids.id, operator_id, occurred_at
  from (
    select distinct id from unnest(coalesce(_user_ids, array[]::uuid[])) as item(id)
  ) ids;

  insert into public.task_group_assignee (task_id, group_id, assigned_by, assigned_at)
  select task_row.id, ids.id, operator_id, occurred_at
  from (
    select distinct id from unnest(coalesce(_group_ids, array[]::bigint[])) as item(id)
  ) ids;

  target_status := task_row.status;
  if task_row.status = 'DRAFT' and (target_user_count > 0 or target_group_count > 0) then
    target_status := 'ASSIGNED';
    perform set_config('lims.task_transition', 'on', true);
    update public.experiment_task
    set status = target_status, updated_at = occurred_at
    where id = task_row.id;
    insert into public.task_status_history (
      task_id, from_status, to_status, operator_id, remark, occurred_at
    ) values (
      task_row.id, task_row.status, target_status, operator_id, '首次分配自动进入已分配', occurred_at
    );
  end if;

  perform public.record_audit_event(
    'task.assign', 'experiment_task', task_row.id::text, 'ASSIGNMENT',
    jsonb_build_object('status', task_row.status),
    jsonb_build_object(
      'status', target_status,
      'user_ids', coalesce(to_jsonb(_user_ids), '[]'::jsonb),
      'group_ids', coalesce(to_jsonb(_group_ids), '[]'::jsonb)
    )
  );

  return jsonb_build_object(
    'taskId', task_row.id,
    'status', target_status,
    'userIds', coalesce(to_jsonb(_user_ids), '[]'::jsonb),
    'groupIds', coalesce(to_jsonb(_group_ids), '[]'::jsonb)
  );
end;
$$;

create or replace function public.transition_task(
  _task_id bigint,
  _to_status varchar,
  _remark text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  task_row public.experiment_task%rowtype;
  operator_id uuid := auth.uid();
  operator_is_assignee boolean;
  has_manage boolean;
  target_status varchar(24) := _to_status;
  occurred_at timestamptz := now();
begin
  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE') then
    raise exception 'Task transition permission denied' using errcode = '42501';
  end if;
  if _to_status not in ('DRAFT', 'ASSIGNED', 'IN_PROGRESS', 'PENDING_REVIEW', 'RETURNED', 'APPROVED', 'ARCHIVED') then
    raise exception 'Invalid task status' using errcode = '22023';
  end if;

  select * into task_row
  from public.experiment_task
  where id = _task_id
  for update;
  if not found then
    raise exception 'Task not found' using errcode = 'P0002';
  end if;

  has_manage := public.has_permission('task.manage');
  operator_is_assignee := exists (
    select 1 from public.task_assignee
    where task_id = task_row.id and user_id = operator_id and unassigned_at is null
  );
  if not has_manage and not operator_is_assignee then
    raise exception 'Task transition permission denied' using errcode = '42501';
  end if;

  if task_row.status = 'DRAFT' and target_status = 'ASSIGNED' then
    if not exists (select 1 from public.task_assignee where task_id = task_row.id and unassigned_at is null)
       and not exists (select 1 from public.task_group_assignee where task_id = task_row.id and unassigned_at is null) then
      raise exception 'Task assignment required' using errcode = '22023';
    end if;
  elsif task_row.status = 'ASSIGNED' and target_status = 'IN_PROGRESS' then
    null;
  elsif task_row.status = 'IN_PROGRESS' and target_status = 'PENDING_REVIEW' then
    null;
  elsif task_row.status = 'PENDING_REVIEW' and target_status in ('APPROVED', 'RETURNED') then
    if not has_manage then
      raise exception 'Task transition permission denied' using errcode = '42501';
    end if;
  elsif task_row.status = 'RETURNED' and target_status = 'IN_PROGRESS' then
    null;
  elsif task_row.status = 'APPROVED' and target_status = 'ARCHIVED' then
    if not has_manage then
      raise exception 'Task transition permission denied' using errcode = '42501';
    end if;
  else
    raise exception 'Invalid task transition' using errcode = '22023';
  end if;

  perform set_config('lims.task_transition', 'on', true);
  update public.experiment_task
  set status = target_status, updated_at = occurred_at
  where id = task_row.id;
  insert into public.task_status_history (
    task_id, from_status, to_status, operator_id, remark, occurred_at
  ) values (
    task_row.id, task_row.status, target_status, operator_id, nullif(trim(_remark), ''), occurred_at
  );
  perform public.record_audit_event(
    'task.read', 'experiment_task', task_row.id::text, 'STATUS',
    jsonb_build_object('status', task_row.status),
    jsonb_build_object('status', target_status, 'remark', nullif(trim(_remark), ''))
  );

  return jsonb_build_object(
    'taskId', task_row.id,
    'fromStatus', task_row.status,
    'toStatus', target_status,
    'operatorId', operator_id,
    'remark', nullif(trim(_remark), ''),
    'occurredAt', occurred_at
  );
end;
$$;

revoke execute on function public.replace_task_assignments(bigint, uuid[], bigint[]) from public;
revoke execute on function public.transition_task(bigint, varchar, text) from public;
grant execute on function public.replace_task_assignments(bigint, uuid[], bigint[]) to authenticated;
grant execute on function public.transition_task(bigint, varchar, text) to authenticated;
