-- Implements FR-ENV-001~005 while reusing lab_laboratory/lab_department from settings.
-- Thresholds are configuration; environment records keep immutable threshold snapshots.

create table if not exists public.environment_threshold (
  id bigint generated by default as identity primary key,
  laboratory_id bigint not null references public.lab_laboratory(id) on delete restrict,
  metric varchar(64) not null,
  unit varchar(16) not null,
  threshold_min numeric(20, 8),
  threshold_max numeric(20, 8),
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (laboratory_id, metric, unit),
  check (threshold_min is not null or threshold_max is not null),
  check (threshold_max is null or threshold_min is null or threshold_max >= threshold_min)
);

create index if not exists idx_environment_threshold_lab_status
  on public.environment_threshold(laboratory_id, status, metric);

alter table public.environment_threshold enable row level security;
alter table public.environment_record enable row level security;
drop policy if exists environment_read_by_permission on public.environment_record;
drop policy if exists environment_manage_by_permission on public.environment_record;
drop policy if exists environment_threshold_read_by_permission on public.environment_threshold;
create policy environment_read_by_permission
on public.environment_record for select to authenticated
using (public.has_permission('resource.read'));
create policy environment_threshold_read_by_permission
on public.environment_threshold for select to authenticated
using (public.has_permission('resource.read'));

revoke all on table public.environment_record from anon, authenticated;
revoke all on table public.environment_threshold from anon, authenticated;
grant select on table public.environment_record to authenticated;
grant select on table public.environment_threshold to authenticated;

create or replace function public.guard_environment_write()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(auth.role(), '') = 'service_role'
     or coalesce(current_setting('lims.environment_write', true), '') = 'on' then
    return coalesce(new, old);
  end if;
  raise exception 'Environment writes must use the environment API' using errcode = '42501';
end;
$$;

drop trigger if exists environment_record_write_guard on public.environment_record;
create trigger environment_record_write_guard
before insert or update or delete on public.environment_record
for each row execute function public.guard_environment_write();

drop trigger if exists environment_threshold_write_guard on public.environment_threshold;
create trigger environment_threshold_write_guard
before insert or update or delete on public.environment_threshold
for each row execute function public.guard_environment_write();

create or replace function public.save_environment_threshold(_threshold_id bigint, _payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  operator_id uuid := auth.uid();
  before_row public.environment_threshold%rowtype;
  after_row public.environment_threshold%rowtype;
  laboratory_id_value bigint;
  metric_value varchar(64);
  unit_value varchar(16);
  min_value numeric;
  max_value numeric;
  status_value varchar(16);
begin
  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE')
     or not public.has_permission('resource.manage') then
    raise exception 'Environment permission denied' using errcode = '42501';
  end if;

  if _threshold_id = 0 then
    laboratory_id_value := nullif(trim(_payload->>'laboratory_id'), '')::bigint;
    metric_value := nullif(trim(_payload->>'metric'), '');
    unit_value := nullif(trim(_payload->>'unit'), '');
    min_value := nullif(trim(_payload->>'threshold_min'), '')::numeric;
    max_value := nullif(trim(_payload->>'threshold_max'), '')::numeric;
    status_value := coalesce(nullif(upper(trim(_payload->>'status')), ''), 'ACTIVE');
  else
    select * into before_row from public.environment_threshold where id = _threshold_id for update;
    if not found then raise exception 'Environment threshold not found' using errcode = 'P0002'; end if;
    if _payload ? 'laboratory_id' or _payload ? 'metric' or _payload ? 'unit' then
      raise exception 'Threshold identity is immutable' using errcode = '55000';
    end if;
    laboratory_id_value := before_row.laboratory_id;
    metric_value := before_row.metric;
    unit_value := before_row.unit;
    min_value := case when _payload ? 'threshold_min' then nullif(trim(_payload->>'threshold_min'), '')::numeric else before_row.threshold_min end;
    max_value := case when _payload ? 'threshold_max' then nullif(trim(_payload->>'threshold_max'), '')::numeric else before_row.threshold_max end;
    status_value := case when _payload ? 'status' then upper(trim(_payload->>'status')) else before_row.status end;
  end if;

  if laboratory_id_value is null or metric_value is null or unit_value is null then
    raise exception 'Laboratory, metric and unit are required' using errcode = '22023';
  end if;
  if not exists (select 1 from public.lab_laboratory where id = laboratory_id_value and status = 'ACTIVE') then
    raise exception 'Laboratory not found or inactive' using errcode = '23514';
  end if;
  if min_value is null and max_value is null then
    raise exception 'At least one environment threshold bound is required' using errcode = '22023';
  end if;
  if max_value is not null and min_value is not null and max_value < min_value then
    raise exception 'Environment threshold maximum must not be below minimum' using errcode = '22023';
  end if;
  if status_value not in ('ACTIVE', 'INACTIVE') then
    raise exception 'Invalid environment threshold status' using errcode = '22023';
  end if;

  perform set_config('lims.environment_write', 'on', true);
  if _threshold_id = 0 then
    insert into public.environment_threshold (
      laboratory_id, metric, unit, threshold_min, threshold_max, status
    ) values (
      laboratory_id_value, metric_value, unit_value, min_value, max_value, status_value
    ) returning * into after_row;
    perform public.record_audit_event(
      'resource.manage', 'environment_threshold', after_row.id::text, 'CREATE', null, to_jsonb(after_row)
    );
  else
    update public.environment_threshold
    set threshold_min = min_value,
        threshold_max = max_value,
        status = status_value
    where id = before_row.id
    returning * into after_row;
    perform public.record_audit_event(
      'resource.manage', 'environment_threshold', after_row.id::text, 'UPDATE', to_jsonb(before_row), to_jsonb(after_row)
    );
  end if;
  return to_jsonb(after_row);
end;
$$;

create or replace function public.record_environment_reading(_payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  operator_id uuid := auth.uid();
  laboratory_id_value bigint := nullif(trim(_payload->>'laboratory_id'), '')::bigint;
  metric_value varchar(64) := nullif(trim(_payload->>'metric'), '');
  unit_value varchar(16) := nullif(trim(_payload->>'unit'), '');
  value_value numeric := nullif(trim(_payload->>'value'), '')::numeric;
  source_type_value varchar(16) := coalesce(nullif(upper(trim(_payload->>'source_type')), ''), 'MANUAL');
  collected_at_value timestamptz := coalesce(nullif(trim(_payload->>'collected_at'), '')::timestamptz, now());
  threshold_min_value numeric;
  threshold_max_value numeric;
  status_value varchar(16);
  record_row public.environment_record%rowtype;
begin
  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE')
     or not public.has_permission('resource.manage') then
    raise exception 'Environment permission denied' using errcode = '42501';
  end if;
  if laboratory_id_value is null or metric_value is null or unit_value is null or value_value is null then
    raise exception 'Laboratory, metric, value and unit are required' using errcode = '22023';
  end if;
  if source_type_value not in ('MANUAL', 'SENSOR', 'API') then
    raise exception 'Invalid environment source type' using errcode = '22023';
  end if;
  if collected_at_value > now() + interval '5 minutes' then
    raise exception 'Environment collected time is in the future' using errcode = '22023';
  end if;
  if not exists (select 1 from public.lab_laboratory where id = laboratory_id_value and status = 'ACTIVE') then
    raise exception 'Laboratory not found or inactive' using errcode = '23514';
  end if;

  select threshold_min, threshold_max
    into threshold_min_value, threshold_max_value
  from public.environment_threshold
  where laboratory_id = laboratory_id_value
    and metric = metric_value
    and unit = unit_value
    and status = 'ACTIVE';

  status_value := case
    when (threshold_min_value is not null and value_value < threshold_min_value)
      or (threshold_max_value is not null and value_value > threshold_max_value) then 'EXCEEDED'
    else 'NORMAL'
  end;

  perform set_config('lims.environment_write', 'on', true);
  insert into public.environment_record (
    laboratory_id, metric, value, unit, threshold_min, threshold_max,
    collected_at, source_type, recorded_by, status
  ) values (
    laboratory_id_value, metric_value, value_value, unit_value, threshold_min_value, threshold_max_value,
    collected_at_value, source_type_value, operator_id, status_value
  ) returning * into record_row;
  perform public.record_audit_event(
    'resource.manage', 'environment_record', record_row.id::text, 'CREATE', null, to_jsonb(record_row)
  );
  return to_jsonb(record_row);
end;
$$;

create or replace function public.get_environment_alerts(_days integer default 30, _laboratory_id bigint default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or not public.has_permission('resource.read') then
    raise exception 'Environment permission denied' using errcode = '42501';
  end if;
  if _days is null or _days < 0 or _days > 365 then
    raise exception 'Environment alert window must be between 0 and 365 days' using errcode = '22023';
  end if;
  return coalesce((
    select jsonb_agg(to_jsonb(alert_row) order by alert_row.collected_at desc, alert_row.id desc)
    from (
      select
        er.id, er.laboratory_id, ll.code as laboratory_code, ll.name as laboratory_name,
        er.metric, er.value, er.unit, er.threshold_min, er.threshold_max,
        er.collected_at, er.source_type, er.recorded_by, er.status
      from public.environment_record er
      join public.lab_laboratory ll on ll.id = er.laboratory_id
      where er.status = 'EXCEEDED'
        and er.collected_at >= current_date - _days
        and (_laboratory_id is null or er.laboratory_id = _laboratory_id)
    ) alert_row
  ), '[]'::jsonb);
end;
$$;

revoke all on function public.save_environment_threshold(bigint, jsonb) from public;
revoke all on function public.record_environment_reading(jsonb) from public;
revoke all on function public.get_environment_alerts(integer, bigint) from public;
grant execute on function public.save_environment_threshold(bigint, jsonb) to authenticated;
grant execute on function public.record_environment_reading(jsonb) to authenticated;
grant execute on function public.get_environment_alerts(integer, bigint) to authenticated;
