-- Basic settings management
-- Implements: FR-SETTING-001~003, NFR-SEC-001~002.

create table public.lab_group (
  id bigint generated by default as identity primary key,
  laboratory_id bigint not null references public.lab_laboratory(id) on delete restrict,
  code varchar(64) not null,
  name varchar(128) not null,
  leader_id uuid references public.sys_user(id) on delete set null,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (laboratory_id, code)
);

create table public.sys_category (
  id bigint generated by default as identity primary key,
  category_type varchar(32) not null,
  code varchar(64) not null,
  name varchar(128) not null,
  parent_id bigint references public.sys_category(id) on delete restrict,
  description varchar(255),
  sort_order integer not null default 0,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (category_type, code)
);

create table public.sys_unit (
  id bigint generated by default as identity primary key,
  code varchar(32) not null unique,
  name varchar(64) not null,
  symbol varchar(32),
  dimension varchar(32),
  sort_order integer not null default 0,
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.sys_parameter (
  id bigint generated by default as identity primary key,
  code varchar(64) not null unique,
  name varchar(128) not null,
  value_type varchar(16) not null check (value_type in ('STRING', 'NUMBER', 'BOOLEAN', 'JSON')),
  value_json jsonb not null,
  description varchar(255),
  status varchar(16) not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_lab_group_laboratory_status on public.lab_group(laboratory_id, status);
create index idx_sys_category_type_parent on public.sys_category(category_type, parent_id, status);
create index idx_sys_unit_status on public.sys_unit(status, sort_order);
create index idx_sys_parameter_status on public.sys_parameter(status, code);

create trigger lab_group_set_updated_at
before update on public.lab_group
for each row execute function public.set_updated_at();

create trigger sys_category_set_updated_at
before update on public.sys_category
for each row execute function public.set_updated_at();

create trigger sys_unit_set_updated_at
before update on public.sys_unit
for each row execute function public.set_updated_at();

create trigger sys_parameter_set_updated_at
before update on public.sys_parameter
for each row execute function public.set_updated_at();

alter table public.lab_group enable row level security;
alter table public.sys_category enable row level security;
alter table public.sys_unit enable row level security;
alter table public.sys_parameter enable row level security;

drop policy if exists laboratory_read_by_permission on public.lab_laboratory;
create policy laboratory_read_by_permission
on public.lab_laboratory for select to authenticated
using (public.has_permission('laboratory.read') or public.has_permission('settings.manage'));

drop policy if exists laboratory_manage_by_permission on public.lab_laboratory;
create policy laboratory_manage_by_permission
on public.lab_laboratory for all to authenticated
using (public.has_permission('laboratory.manage') or public.has_permission('settings.manage'))
with check (public.has_permission('laboratory.manage') or public.has_permission('settings.manage'));

drop policy if exists department_read_by_permission on public.lab_department;
create policy department_read_by_permission
on public.lab_department for select to authenticated
using (public.has_permission('laboratory.read') or public.has_permission('settings.manage'));

drop policy if exists department_manage_by_permission on public.lab_department;
create policy department_manage_by_permission
on public.lab_department for all to authenticated
using (public.has_permission('laboratory.manage') or public.has_permission('settings.manage'))
with check (public.has_permission('laboratory.manage') or public.has_permission('settings.manage'));

create policy lab_group_settings_manage
on public.lab_group for all to authenticated
using (public.has_permission('settings.manage'))
with check (public.has_permission('settings.manage'));

create policy sys_category_settings_manage
on public.sys_category for all to authenticated
using (public.has_permission('settings.manage'))
with check (public.has_permission('settings.manage'));

create policy sys_unit_settings_manage
on public.sys_unit for all to authenticated
using (public.has_permission('settings.manage'))
with check (public.has_permission('settings.manage'));

create policy sys_parameter_settings_manage
on public.sys_parameter for all to authenticated
using (public.has_permission('settings.manage'))
with check (public.has_permission('settings.manage'));

create or replace function public.record_audit_event(
  _required_permission varchar,
  _object_type varchar,
  _object_id varchar,
  _action varchar,
  _before_json jsonb default null,
  _after_json jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if _required_permission not in ('auth.user.manage', 'auth.role.manage', 'settings.manage') then
    raise exception 'Unsupported audit permission' using errcode = '22023';
  end if;

  if not public.has_permission(_required_permission) then
    raise exception 'Permission denied' using errcode = '42501';
  end if;

  insert into public.audit_log (
    operator_id,
    object_type,
    object_id,
    action,
    before_json,
    after_json
  )
  values (
    auth.uid(),
    _object_type,
    _object_id,
    _action,
    _before_json,
    _after_json
  );
end;
$$;

grant execute on function public.record_audit_event(varchar, varchar, varchar, varchar, jsonb, jsonb) to authenticated;
