-- Implements FR-REPORT-001~006, FR-AUDIT-005, AC-REPORT-001 and NFR-SEC-002.
-- Report payloads are immutable snapshots; all state changes use transaction RPCs.

alter table public.experiment_report
  add column if not exists report_payload jsonb;

update public.experiment_report
set report_payload = '{}'::jsonb
where report_payload is null;

alter table public.experiment_report
  alter column report_payload set default '{}'::jsonb,
  alter column report_payload set not null;

alter table public.experiment_report
  drop constraint if exists experiment_report_status_check;
alter table public.experiment_report
  add constraint experiment_report_status_check
  check (status in ('DRAFT', 'REVIEW', 'PUBLISHED', 'ARCHIVED'));

create table if not exists public.experiment_report_history (
  id bigint generated by default as identity primary key,
  report_id bigint not null references public.experiment_report(id) on delete cascade,
  from_status varchar(16),
  to_status varchar(16) not null,
  operator_id uuid not null references public.sys_user(id) on delete restrict,
  remark text,
  occurred_at timestamptz not null default now()
);

create index if not exists idx_report_history_report_time
  on public.experiment_report_history(report_id, occurred_at desc, id desc);

alter table public.experiment_report enable row level security;
alter table public.experiment_report_history enable row level security;
drop policy if exists report_read_by_permission on public.experiment_report;
drop policy if exists report_manage_by_permission on public.experiment_report;
drop policy if exists report_update_by_permission on public.experiment_report;
drop policy if exists report_history_read_by_permission on public.experiment_report_history;
create policy report_read_by_permission
on public.experiment_report for select to authenticated
using (public.has_permission('report.read'));
create policy report_history_read_by_permission
on public.experiment_report_history for select to authenticated
using (public.has_permission('report.read'));

revoke all on table public.experiment_report from anon, authenticated;
revoke all on table public.experiment_report_history from anon, authenticated;
grant select on table public.experiment_report to authenticated;
grant select on table public.experiment_report_history to authenticated;

create or replace function public.guard_experiment_report_immutable()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(current_setting('lims.report_transition', true), '') <> 'on' then
    raise exception 'Report records are immutable' using errcode = '55000';
  end if;
  return coalesce(new, old);
end;
$$;

drop trigger if exists experiment_report_immutable on public.experiment_report;
create trigger experiment_report_immutable
before update or delete on public.experiment_report
for each row execute function public.guard_experiment_report_immutable();

create or replace function public.guard_experiment_report_history_immutable()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  raise exception 'Report history is immutable' using errcode = '55000';
end;
$$;

drop trigger if exists experiment_report_history_immutable on public.experiment_report_history;
create trigger experiment_report_history_immutable
before update or delete on public.experiment_report_history
for each row execute function public.guard_experiment_report_history_immutable();

create or replace function public.record_audit_event(
  _required_permission varchar,
  _object_type varchar,
  _object_id varchar,
  _action varchar,
  _before_json jsonb default null,
  _after_json jsonb default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if _required_permission not in (
    'auth.user.manage', 'auth.role.manage', 'settings.manage',
    'resource.manage', 'project.manage', 'task.read', 'task.manage', 'task.assign',
    'sample.manage', 'data.manage', 'review.manage', 'report.manage', 'report.publish'
  ) then
    raise exception 'Unsupported audit permission' using errcode = '22023';
  end if;

  if not public.has_permission(_required_permission) then
    raise exception 'Permission denied' using errcode = '42501';
  end if;

  insert into public.audit_log (
    operator_id, object_type, object_id, action, before_json, after_json
  ) values (
    auth.uid(), _object_type, _object_id, _action, _before_json, _after_json
  );
end;
$$;

create or replace function public.generate_report(_task_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  operator_id uuid := auth.uid();
  task_row public.experiment_task%rowtype;
  latest_review_result varchar(16);
  report_row public.experiment_report%rowtype;
  report_code_value varchar(32);
  next_version integer;
  generated_at timestamptz := now();
  sample_payload jsonb;
  data_payload jsonb;
  review_payload jsonb;
  payload jsonb;
begin
  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE')
     or not public.has_permission('report.manage') then
    raise exception 'Report generation permission denied' using errcode = '42501';
  end if;

  select * into task_row
  from public.experiment_task
  where id = _task_id
  for update;
  if not found then
    raise exception 'Report task not found' using errcode = 'P0002';
  end if;

  select rr.result into latest_review_result
  from public.result_review rr
  where rr.task_id = task_row.id
  order by rr.reviewed_at desc, rr.id desc
  limit 1;
  if task_row.status <> 'APPROVED' or latest_review_result <> 'APPROVED' then
    raise exception 'Only approved tasks can generate reports' using errcode = '55000';
  end if;

  report_code_value := format('RPT-%s', task_row.id)::varchar(32);
  select coalesce(max(version_no), 0) + 1 into next_version
  from public.experiment_report
  where task_id = task_row.id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', s.id,
    'sampleCode', s.sample_code,
    'name', s.name,
    'specification', s.specification,
    'batchNo', s.batch_no,
    'quantity', s.quantity,
    'unit', s.unit,
    'status', s.status
  ) order by s.id), '[]'::jsonb)
  into sample_payload
  from public.task_sample ts
  join public.sample s on s.id = ts.sample_id
  where ts.task_id = task_row.id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', d.id,
    'sampleId', d.sample_id,
    'instrumentId', d.instrument_id,
    'dataType', d.data_type,
    'metricName', d.metric_name,
    'rawValue', d.raw_value,
    'processedValue', d.processed_value,
    'unit', d.unit,
    'sourceType', d.source_type,
    'collectedAt', d.collected_at,
    'recordedBy', d.recorded_by,
    'remark', d.remark
  ) order by d.id), '[]'::jsonb)
  into data_payload
  from public.experiment_data d
  where d.task_id = task_row.id;

  select coalesce(jsonb_agg(jsonb_build_object(
    'id', rr.id,
    'reviewerId', rr.reviewer_id,
    'result', rr.result,
    'comment', rr.comment,
    'reviewedAt', rr.reviewed_at,
    'createdAt', rr.created_at
  ) order by rr.reviewed_at, rr.id), '[]'::jsonb)
  into review_payload
  from public.result_review rr
  where rr.task_id = task_row.id;

  payload := jsonb_build_object(
    'task', jsonb_build_object(
      'id', task_row.id,
      'taskCode', task_row.task_code,
      'projectId', task_row.project_id,
      'methodId', task_row.method_id,
      'name', task_row.name,
      'priority', task_row.priority,
      'status', task_row.status,
      'remark', task_row.remark
    ),
    'samples', sample_payload,
    'data', data_payload,
    'reviews', review_payload
  );

  insert into public.experiment_report (
    report_code, task_id, version_no, status, report_payload, generated_by, generated_at
  ) values (
    report_code_value, task_row.id, next_version, 'DRAFT', payload, operator_id, generated_at
  ) returning * into report_row;

  insert into public.experiment_report_history (
    report_id, from_status, to_status, operator_id, remark, occurred_at
  ) values (
    report_row.id, null, report_row.status, operator_id, '报告生成', generated_at
  );

  perform public.record_audit_event(
    'report.manage', 'experiment_report', report_row.id::text, 'CREATE', null,
    jsonb_build_object('taskId', task_row.id, 'reportCode', report_row.report_code, 'versionNo', report_row.version_no)
  );

  return to_jsonb(report_row);
end;
$$;

create or replace function public.submit_report_for_review(_report_id bigint, _remark text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  operator_id uuid := auth.uid();
  report_row public.experiment_report%rowtype;
  occurred_at timestamptz := now();
  normalized_remark text := nullif(trim(_remark), '');
begin
  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE')
     or not public.has_permission('report.manage') then
    raise exception 'Report review permission denied' using errcode = '42501';
  end if;

  select * into report_row from public.experiment_report where id = _report_id for update;
  if not found then raise exception 'Report not found' using errcode = 'P0002'; end if;
  if report_row.status <> 'DRAFT' then
    raise exception 'Report is not a draft' using errcode = '55000';
  end if;

  perform set_config('lims.report_transition', 'on', true);
  update public.experiment_report
  set status = 'REVIEW'
  where id = report_row.id;

  insert into public.experiment_report_history(report_id, from_status, to_status, operator_id, remark, occurred_at)
  values (report_row.id, report_row.status, 'REVIEW', operator_id, normalized_remark, occurred_at);
  perform public.record_audit_event(
    'report.manage', 'experiment_report', report_row.id::text, 'SUBMIT_REVIEW',
    jsonb_build_object('status', report_row.status), jsonb_build_object('status', 'REVIEW', 'remark', normalized_remark)
  );
  select * into report_row from public.experiment_report where id = _report_id;
  return to_jsonb(report_row);
end;
$$;

create or replace function public.publish_report(_report_id bigint, _remark text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  operator_id uuid := auth.uid();
  report_row public.experiment_report%rowtype;
  previous_row public.experiment_report%rowtype;
  occurred_at timestamptz := now();
  normalized_remark text := nullif(trim(_remark), '');
begin
  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE')
     or not public.has_permission('report.publish') then
    raise exception 'Report publish permission denied' using errcode = '42501';
  end if;

  select * into report_row from public.experiment_report where id = _report_id for update;
  if not found then raise exception 'Report not found' using errcode = 'P0002'; end if;
  if report_row.status <> 'REVIEW' then
    raise exception 'Report is not ready for publishing' using errcode = '55000';
  end if;

  perform set_config('lims.report_transition', 'on', true);
  for previous_row in
    select * from public.experiment_report
    where report_code = report_row.report_code and status = 'PUBLISHED' and id <> report_row.id
    for update
  loop
    update public.experiment_report
    set status = 'ARCHIVED', archived_at = occurred_at
    where id = previous_row.id;
    insert into public.experiment_report_history(report_id, from_status, to_status, operator_id, remark, occurred_at)
    values (previous_row.id, previous_row.status, 'ARCHIVED', operator_id, '新版本发布自动归档', occurred_at);
    perform public.record_audit_event(
      'report.publish', 'experiment_report', previous_row.id::text, 'ARCHIVE',
      jsonb_build_object('status', previous_row.status), jsonb_build_object('status', 'ARCHIVED', 'remark', normalized_remark)
    );
  end loop;

  update public.experiment_report
  set status = 'PUBLISHED', published_at = occurred_at, archived_at = null
  where id = report_row.id;
  insert into public.experiment_report_history(report_id, from_status, to_status, operator_id, remark, occurred_at)
  values (report_row.id, report_row.status, 'PUBLISHED', operator_id, normalized_remark, occurred_at);
  perform public.record_audit_event(
    'report.publish', 'experiment_report', report_row.id::text, 'PUBLISH',
    jsonb_build_object('status', report_row.status), jsonb_build_object('status', 'PUBLISHED', 'remark', normalized_remark)
  );
  select * into report_row from public.experiment_report where id = _report_id;
  return to_jsonb(report_row);
end;
$$;

create or replace function public.archive_report(_report_id bigint, _remark text default null)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  operator_id uuid := auth.uid();
  report_row public.experiment_report%rowtype;
  occurred_at timestamptz := now();
  normalized_remark text := nullif(trim(_remark), '');
begin
  if operator_id is null
     or not exists (select 1 from public.sys_user where id = operator_id and status = 'ACTIVE')
     or not public.has_permission('report.publish') then
    raise exception 'Report archive permission denied' using errcode = '42501';
  end if;

  select * into report_row from public.experiment_report where id = _report_id for update;
  if not found then raise exception 'Report not found' using errcode = 'P0002'; end if;
  if report_row.status <> 'PUBLISHED' then
    raise exception 'Only published reports can be archived' using errcode = '55000';
  end if;

  perform set_config('lims.report_transition', 'on', true);
  update public.experiment_report
  set status = 'ARCHIVED', archived_at = occurred_at
  where id = report_row.id;
  insert into public.experiment_report_history(report_id, from_status, to_status, operator_id, remark, occurred_at)
  values (report_row.id, report_row.status, 'ARCHIVED', operator_id, normalized_remark, occurred_at);
  perform public.record_audit_event(
    'report.publish', 'experiment_report', report_row.id::text, 'ARCHIVE',
    jsonb_build_object('status', report_row.status), jsonb_build_object('status', 'ARCHIVED', 'remark', normalized_remark)
  );
  select * into report_row from public.experiment_report where id = _report_id;
  return to_jsonb(report_row);
end;
$$;

revoke all on function public.generate_report(bigint) from public;
revoke all on function public.submit_report_for_review(bigint, text) from public;
revoke all on function public.publish_report(bigint, text) from public;
revoke all on function public.archive_report(bigint, text) from public;
grant execute on function public.generate_report(bigint) to authenticated;
grant execute on function public.submit_report_for_review(bigint, text) to authenticated;
grant execute on function public.publish_report(bigint, text) to authenticated;
grant execute on function public.archive_report(bigint, text) to authenticated;
